logging:
  level:
    blog: WARN
    org:
      hibernate:
        SQL: debug
        type:
          descriptor: TRACE
      nodeValue: WARN
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:covid_19_statistics
    username: ${DATABASE_ROOT_USER}
    password: ${DATABASE_ROOT_PASS}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
server:
  port: 8080
